title = "Johan Gall"
description = "aka jojo, lucyjojo, freakhill, seku"
base_url = "https://www.johangall.com"

compile_sass = true
highlight_code = true
build_search_index = false

theme = "hyde"

taxonomies = [
  {name = "tags", rss = true},
]

[extra]
hyde_links = [
{url = "https://www.youtube.com/watch?v=NYgq75uIMUk", name = "SFV beginner guide"},
{url = "https://github.com/freakhill/jojolisp", name = "Jojolisp's github repo"},
{url = "https://www.twitch.tv/lucyjojo", name = "Twitch channel"},
{url = "http://www.metro.tokyo.jp/english/guide/bosai/index.html", name = "Disaster preparedness Tokyo" },
]
hyde_theme = "theme-base-0e"
hyde_reverse = true
